export default {
    '/collections/': [
        {
            text: '一些示例',
            items: [
                {text: "计算 GitHub 事件得分总和", link: "/collections/examples/format-github-events-score"},
                {
                    text: "格式化计算两个数组的数据",
                    link: "/collections/examples/format-calculate-the-data-of-the-two-arrays"
                },
                {text: "通过值获取对应key", link: "/collections/examples/get-the-corresponding-key-by-value"},
                {text: "map 格式化数据", link: "/collections/examples/map-format"},
                {text: "格式化 Markdown 数据列表", link: "/collections/examples/markdown-format"},
                {text: "订单数据汇总", link: "/collections/examples/order-info-summary"},
                {text: "通过原数组组装成其他数组格式", link: "/collections/examples/using-reduce-create-lookup-array"},
                {text: "sum 求和数组项", link: "/collections/examples/using-sum-method"},
            ],
        },
        {
            text: '集合方法',
            items: [
                {text: "all", link: "/collections/all"},
                {text: "average", link: "/collections/avg"},
                {text: "avg", link: "/collections/avg"},
                {text: "chunk", link: "/collections/chunk"},
                {text: "chunkWhile", link: "/collections/chunkWhile"},
                {text: "collapse", link: "/collections/collapse"},
                {text: "collect", link: "/collections/collect"},
                {text: "combine", link: "/collections/combine"},
                {text: "concat", link: "/collections/concat"},
                {text: "contains", link: "/collections/contains"},
                {text: 'containsOneItem', link: '/collections/containsOneItem'},
                {text: "containsStrict", link: "/collections/containsStrict"},
                {text: "count", link: "/collections/count"},
                {text: "countBy", link: "/collections/countBy"},
                {text: "crossJoin", link: "/collections/crossJoin"},
                {text: "dd", link: "/collections/dd"},
                {text: "diff", link: "/collections/diff"},
                {text: "diffAssoc", link: "/collections/diffAssoc"},
                {text: "diffAssocUsing", link: "/collections/diffAssocUsing"},
                {text: "diffKeys", link: "/collections/diffKeys"},
                {text: "diffKeysUsing", link: "/collections/diffKeysUsing"},
                {text: "diffUsing", link: "/collections/diffUsing"},
                {text: "doesntContain", link: "/collections/doesntContain"},
                {text: "dump", link: "/collections/dump"},
                {text: "duplicates", link: "/collections/duplicates"},
                {text: "duplicates", link: "/collections/duplicates"},
                {text: "duplicatesStrict", link: "/collections/duplicatesStrict"},
                {text: "each", link: "/collections/each"},
                {text: "eachSpread", link: "/collections/eachSpread"},
                {text: "every", link: "/collections/every"},
                {text: "except", link: "/collections/except"},
                {text: "filter", link: "/collections/filter"},
                {text: "first", link: "/collections/first"},
                {text: "firstOrFail", link: "/collections/firstOrFail"},
                {text: "firstWhere", link: "/collections/firstWhere"},
                {text: "flatMap", link: "/collections/flatMap"},
                {text: "flatten", link: "/collections/flatten"},
                {text: "flip", link: "/collections/flip"},
                {text: "forget", link: "/collections/forget"},
                {text: "forPage", link: "/collections/forPage"},
                {text: "get", link: "/collections/get"},
                {text: "groupBy", link: "/collections/groupBy"},
                {text: "has", link: "/collections/has"},
                {text: "hasAny", link: "/collections/hasAny"},
                {text: "implode", link: "/collections/implode"},
                {text: "intersect", link: "/collections/intersect"},
                {text: "intersectByKeys", link: "/collections/intersectByKeys"},
                {text: "isEmpty", link: "/collections/isEmpty"},
                {text: "isNotEmpty", link: "/collections/isNotEmpty"},
                {text: "keyBy", link: "/collections/keyBy"},
                {text: "keys", link: "/collections/keys"},
                {text: "last", link: "/collections/last"},
                {text: "lazy", link: "/collections/lazy"},
                {text: "macro", link: "/collections/macro"},
                {text: 'make', link: '/collections/make'},
                {text: "map", link: "/collections/map"},
                {text: "mapInto", link: "/collections/mapInto"},
                {text: "mapSpread", link: "/collections/mapSpread"},
                {text: "mapToDictionary", link: "/collections/mapToDictionary"},
                {text: "mapToGroups", link: "/collections/mapToGroups"},
                {text: "mapWithKeys", link: "/collections/mapWithKeys"},
                {text: "max", link: "/collections/max"},
                {text: "median", link: "/collections/median"},
                {text: "merge", link: "/collections/merge"},
                {text: "mergeRecursive", link: "/collections/mergeRecursive"},
                {text: "min", link: "/collections/min"},
                {text: "mode", link: "/collections/mode"},
                {text: "nth", link: "/collections/nth"},
                {text: "only", link: "/collections/only"},
                {text: "pad", link: "/collections/pad"},
                {text: "partition", link: "/collections/partition"},
                {text: "pipe", link: "/collections/pipe"},
                {text: "pipeInto", link: "/collections/pipeInto"},
                {text: "pipeThrough", link: "/collections/pipeThrough"},
                {text: "pluck", link: "/collections/pluck"},
                {text: "pop", link: "/collections/pop"},
                {text: "prepend", link: "/collections/prepend"},
                {text: "pull", link: "/collections/pull"},
                {text: "push", link: "/collections/push"},
                {text: "put", link: "/collections/put"},
                {text: "random", link: "/collections/random"},
                {text: "reduce", link: "/collections/reduce"},
                {text: "reduceSpread", link: "/collections/reduceSpread"},
                {text: "reject", link: "/collections/reject"},
                {text: "replace", link: "/collections/replace"},
                {text: "replaceRecursive", link: "/collections/replaceRecursive"},
                {text: "reverse", link: "/collections/reverse"},
                {text: "search", link: "/collections/search"},
                {text: "shift", link: "/collections/shift"},
                {text: "shuffle", link: "/collections/shuffle"},
                {text: "skip", link: "/collections/skip"},
                {text: "skipUntil", link: "/collections/skipUntil"},
                {text: "skipWhile", link: "/collections/skipWhile"},
                {text: "slice", link: "/collections/slice"},
                {text: "sliding", link: "/collections/sliding"},
                {text: "sole", link: "/collections/sole"},
                {text: "sort", link: "/collections/sort"},
                {text: "sortBy", link: "/collections/sortBy"},
                {text: "sortByDesc", link: "/collections/sortByDesc"},
                {text: "sortDesc", link: "/collections/sortDesc"},
                {text: "sortKeys", link: "/collections/sortKeys"},
                {text: "sortKeysDesc", link: "/collections/sortKeysDesc"},
                {text: "sortKeysUsing", link: "/collections/sortKeysUsing"},
                {text: "splice", link: "/collections/splice"},
                {text: "split", link: "/collections/split"},
                {text: "splitIn", link: "/collections/splitIn"},
                {text: "sum", link: "/collections/sum"},
                {text: "take", link: "/collections/take"},
                {text: "takeUntil", link: "/collections/takeUntil"},
                {text: "takeWhile", link: "/collections/takeWhile"},
                {text: "tap", link: "/collections/tap"},
                {text: "times", link: "/collections/times"},
                {text: "toArray", link: "/collections/toArray"},
                {text: "toJson", link: "/collections/toJson"},
                {text: "transform", link: "/collections/transform"},
                {text: "undot", link: "/collections/undot"},
                {text: "union", link: "/collections/union"},
                {text: "unique", link: "/collections/unique"},
                {text: "uniqueStrict", link: "/collections/uniqueStrict"},
                {text: "unless", link: "/collections/unless"},
                {text: "unwrap", link: "/collections/unwrap"},
                {text: "value", link: "/collections/value"},
                {text: "values", link: "/collections/values"},
                {text: "when", link: "/collections/when"},
                {text: "whenEmpty", link: "/collections/whenEmpty"},
                {text: "whenNotEmpty", link: "/collections/whenNotEmpty"},
                {text: "where", link: "/collections/where"},
                {text: "whereBetween", link: "/collections/whereBetween"},
                {text: "whereIn", link: "/collections/whereIn"},
                {text: "whereInStrict", link: "/collections/whereInStrict"},
                {text: "whereInstanceOf", link: "/collections/whereInstanceOf"},
                {text: "whereNotBetween", link: "/collections/whereNotBetween"},
                {text: "whereNotIn", link: "/collections/whereNotIn"},
                {text: "whereNotInStrict", link: "/collections/whereNotInStrict"},
                {text: "whereNotNull", link: "/collections/whereNotNull"},
                {text: "whereNull", link: "/collections/whereNull"},
                {text: "whereStrict", link: "/collections/whereStrict"},
                {text: "wrap", link: "/collections/wrap"},
                {text: "zip", link: "/collections/zip"},
            ],
        },
    ],
    '/model/': [
        {
            text: '关联关系',
            items: [
                {text: "一对一", link: "/model/relationships/01-has-one"},
                {text: "一对多", link: "/model/relationships/02-has-many"},
                {text: "许多之一", link: "/model/relationships/03-has-one-of-many"},
                {text: "远层一对一", link: "/model/relationships/04-has-one-through"},
                {text: "远层一对多", link: "/model/relationships/05-has-many-through"},
                {text: "多对多", link: "/model/relationships/06-belongs-to-many"},
                {text: "多态一对一", link: "/model/relationships/07-morph-one"},
                {text: "多态一对多", link: "/model/relationships/08-morph-many"},
                {text: "多态其中之一", link: "/model/relationships/09-one-of-many"},
                {text: "多态多对多", link: "/model/relationships/10-morph-to-many"},
            ],
        },
        {
            text: '基础',
            items: [
                {text: "模型缓存", link: "/model/laravel-model-caching"},
                {text: "模型事件", link: "/model/laravel-model-events"},
                {text: "模型观察者", link: "/model/laravel-model-observers"},
                {text: "数据库优化建议", link: "/model/some-tips-for-optimize-database-queries"},
            ],
        },
    ],
    '/packages/': [
        {
            text: 'Laravel',
            items: [
                {text: "Pail", link: "/packages/laravel/pail"},
                {text: "Pint", link: "/packages/laravel/pint"},
            ]
        },
        {
            text: 'Spatie',
            items: [
                {text: "Login Link", link: "/packages/spatie/laravel-login-link"},
                {text: "Backup", link: "/packages/spatie/laravel-backup"},
                {text: "Data", link: "/packages/spatie/laravel-data"},
            ]
        },
        {
            text: 'Others',
            items: [
                {text: "Sushi 🍣", link: "/packages/others/sushi"},
                {text: "Livewire Missing Assertions", link: "/packages/others/missing-livewire-assertions"},
            ],
        },
    ],
    '/partials/': [
        {
            text: "",
            items: [
                {text: 'Migrations 迁移', link: "/partials/migrations"},
                {text: "Model 模型", link: "/partials/model"},
                {text: "Model Relations 模型关系", link: "/partials/model-relations"},
                {text: "Views 视图", link: "/partials/views"},
                {text: "Validation 验证", link: "/partials/validation"},
                {text: "URL 生成", link: "/partials/urls"},
                {text: "Routing 路由", link: "/partials/routing"},
                {text: "Testing 测试", link: "/partials/testing"},
                {text: "Factories 工厂", link: "/partials/factories"},
            ],
        }
    ],
    '/tips/': [
        {
            text: '',
            items: [
                {text: "DB 模型和 Eloquent", link: "/tips/db-models-and-eloquent"},
                {text: "优化 Factory 数据库批量插入", link: '/tips/optimize-factory-database-batch-insert'},
                {text: "重用环境变量值", link: '/tips/reuse-the-environment-variable-value'},
                {
                    text: "使用 Laravel simple-excel 处理大型 CSV 文件",
                    link: '/tips/process-large-csv-files-with-laravel-using-simple-excel'
                },
                {text: "Laravel 模块化开发", link: 'tips/modular-laravel'}
            ]
        }
    ],
    '/others/': [
        {
            items: [
                {text: "创建自定义 Facade", link: "/others/laravel-create-custom-facade-test-demo"},
                {text: "添加全局函数", link: "/others/laravel-import-custom-function-file"},
                {text: "自定义异常", link: "/others/using-custom-exceptions-to-write-better-and-clearer-code"},
                {text: "使用 pest 测试 Laravel API", link: "/others/unit-test-laravel-api-pest-framework.md"},
                {text: "自定义逻辑 Macros", link: "/others/macros.md"},
                {
                    text: '使用 Alpine.js 滚动到验证错误',
                    link: "/others/scroll-to-validation-error-in-laravel-using-alpinejs"
                },
                {text: '生成视图的 Artisan 命令', link: "/others/artisan-command-to-generate-views-in-laravel"},
            ],
        },
        {
            text: 'Helpers',
            items: [
                {text: "数组 Arrays", link: '/others/helpers/arrays'},
                {text: "数字 Numbers", link: '/others/helpers/numbers'},
                {text: "暂停执行 Sleep", link: '/others/helpers/sleep'},
            ]
        }
    ],
};